# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe31b12555c373f8415e5ebcc8bc0dd975b601a19445050f554fc461424a894fb5b103232f19e4c710b0befcddb3f30a813dd5407d82d5e5fe8265e03a9ded6

test:
  secret_key_base: 2d9477487edeb674de0f52a91e7c5d0c0f8b2b8f3de6ff12c74607c5904fa3950b704134cda73d98b55091fcf695e8e6fa6d01aab8a0a560b2604b045585f362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
